### ISSUE TITLE
mapOverlay failing unit test

### ISSUE THREAD

**Issue by ksterne** [vtsuperdarn/davitpy#201]
Working on the #198 0.5-release pull request, finding the `mapOverlay.py` unit test or running `python mapOverlay.py` fails with an error of:

  > File "/usr/local/lib/python2.7/dist-packages/davitpy-0.5-py2.7-linux x86_64.egg/davitpy/utils/plotUtils.py", line 282, in _readboundarydata
>    newgeom = _geoslib.Polygon(b).fix()
> AttributeError: '_geoslib.Polygon' object has no attribute 'fix'

Not in the scope of the release, but should be fixed whenever we return to updating develop branch.

**Comment by asreimer** [comment]
Using #239, this bug is fixed.
